---
- name: Install redis
  tags:
    - system
    - pkgs
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - redis
    - ruby26-redis
    - ruby26-redis-namespace

- name: enable redis
  service:
    name: redis
    enabled: yes
    state: started

